apiVersion: apps/v1
kind: Deployment
metadata: 
  name: challan-ws-public-deployment
  labels:
    app: challan-ws-public
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challan-ws-public
  template:
    metadata:
      labels:
        app: challan-ws-public
    spec:
      containers: 
        - name: challan-ws-public
          image: bezve01/challan_ws_public:latest
          ports:
            - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: challan-ws-public
  namespace: default
spec:
  selector:
    app: challan-ws-public
  ports:
    - protocol: TCP
      # Pod Port within the cluster
      port: 8004
      # targetPort is application listening port or containerPort
      targetPort: 8004   
  type: NodePort