apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dynamodb-deployment
  labels:
    app: dynamodb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers: 
        - name: dynamodb
          image: amazon/dynamodb-local:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
  namespace: default
spec:
  selector:
    app: dynamodb
  ports:
    - protocol: TCP
      # Pod Port within the cluster
      port: 8000
      # targetPort is application listening port or containerPort
      targetPort: 8000  
  type: NodePort