apiVersion: apps/v1
kind: Deployment
metadata: 
  name: vehicle-deployment
  labels:
    app: vehicle
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehicle
  template:
    metadata:
      labels:
        app: vehicle
    spec:
      containers: 
        - name: vehicle
          image: bezve01/vehicle:latest
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: vehicle
  namespace: default
spec:
  selector:
    app: vehicle
  ports:
    - protocol: TCP
      # Pod Port within the cluster
      port: 8001
      # targetPort is application listening port or containerPort
      targetPort: 8001
  type: NodePort