apiVersion: apps/v1
kind: Deployment
metadata: 
  name: challan-ws-deployment
  labels:
    app: challan-ws
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: challan-ws
  template:
    metadata:
      labels:
        app: challan-ws
    spec:
      containers: 
        - name: challan-ws
          image: bezve01/challan_ws:latest
          ports:
            - containerPort: 8003
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: challan-ws
  namespace: default
spec:
  selector:
    app: challan-ws
  ports:
    - protocol: TCP
      # Pod Port within the cluster
      port: 8003
      # targetPort is application listening port or containerPort
      targetPort: 8003   
  type: NodePort